---
title: 'BIOL 720 Assignment #5'
author: "Elise Millar"
date: "November 28, 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 2

```{r}

diploid_sim <- function(p0 = 0.1, w1 = 1, w2 = 0.95, w3 = 0.9,  n = 500) {
  
    p <- rep(NA,n)  
    w_bar <- rep(NA, n)
     
   	p[1] <- p0 

	  w_bar[1] <- (p[1]^2*w1) + ((2*p[1]*(1-p[1]))*w2) + ((1-p[1])^2)*w3
	
	for (i in 2:n) {
		w_bar[i - 1] <- (p[i-1]^2*w1) + ((2*p[i-1]*(1-p[i-1]))*w2) + ((1-p[i-1])^2)*w3 
		p[i] <- ((p[i - 1]^2) * (w1/w_bar[i - 1])) + (p[i-1]*(1-p[i-1]))*(w2/w_bar[i-1])
	}
	  
    if (p > 0.9999) {
    fixation <- min(which.max(p > 0.9999))
    print("fixation for A1 occurs approximately at generation", fixation )	
    } else {
        maxAlleleFreq <- max(p)
    	print("fixation of A1 does not occur, max. allele frequency is")
    	print(maxAlleleFreq, digits = 2) 
    }
	  
plot(x = 1:n, y = p, 
     xlab="Generations", 
	 ylab="Allele frequency (p)", 
	 pch = 20, col = "red", cex.lab = 1.5)
}


diploid_sim()

```

# Question 3

```{r}

gen_drift <- function(a, HD, ind, gen) {
  alleles <- c(sample(c("a", "A"), 
                      size = HD*(ind), 
                      replace = TRUE, 
                      prob = c(a, 1 - a)))

  allelefreq <- matrix(data = NA, nrow = gen, ncol = 2)

  for(i in 1:gen){
    alleles <- sample(alleles, HD*ind, replace=TRUE)
    allelefreq[i,2] <- (length(alleles[alleles =="A"]))/(HD*(ind))
    allelefreq[i,1] <- (length(alleles[alleles =="a"]))/(HD*(ind))
  }

 a <- allelefreq[,1]
 A <- allelefreq[,2]

 plot(1, type="n", xlim=c(1,gen), ylim=c(0,1), xlab="generation", ylab="Frequency Of Alleles")
 lines(x = A, type = "l", col = "red")
 lines(x = a, type = "l", col = "blue")
 legend("topleft", legend=c("A Frequency", "a Frequency"),
       col=c("red", "blue"), lty=1, cex=0.8)
}

gen_drift(0.5, 2, 20, 100)

```


# Question 4

```{r}

allele_lost <- function(A, gen, runs) {
  
Aprop1 <- matrix(data = NA, nrow = runs, ncol = 1)

for(j in 1:runs){
alleles <- c(sample(c("a", "A"), size = 400, replace = TRUE, prob = c(1 - A, A)))
Aprop <- integer()


for(i in 1:gen) {
alleles <- sample(alleles, 400, replace=TRUE)
Afreq <- (length(alleles[alleles == "A"]))/(400)
Aprop[i] <- Afreq
}

Aprop1[j,1] <- tail(Aprop, n = 1)
}

zerocount <- (length(which(Aprop1[,1] == "0")))
print("Proportion of simulation where pA = 0")
print(zerocount/runs)
}


allele_lost(0.5, 100, 1000)


```

# Question 5

```{r}

allele_traject <- function(A, gen, runs) {

plot(1, type = "n", xlim = c(1,gen), ylim = c(0,1), xlab = "Generation", ylab = "Allele Frequency", main = "Influence of Genetic Drift on Allele Frequencies")

for(j in 1:runs){
alleles <- c(sample(c("a", "A"), size = 400, replace = TRUE, prob = c(1 - A, A)))
Aprop <- integer()


for(i in 1:gen) {
alleles <- sample(alleles, 400, replace=TRUE)
Afreq <- (length(alleles[alleles =="A"]))/(400)
Aprop[i] <- Afreq
}
lines(x = Aprop, type = "l", col = sample(rainbow(n= runs)), lwd=2)

}

}

allele_traject(0.5, 100, 100)

```

# Question 6

# from question (stochastic):
x <- seq(from =1, to = 10, length.out = 20) # length.out is how many observations we will have 
a <- 0.5 # intercept 
b <- 0.1 # slope 
y_deterministic <- a + b*x

y_simulated <- rnorm(length(x), mean = y_deterministic, sd = 2)

mod_sim <- lm(y_simulated ~ x) 
p_val_slope <- summary(mod_sim)$coef[2,4] # extracts the p-value 
p_val_slope



```{r}

p_val <- function(a, b, n, rse){
  
set.seed(720)
x <- seq(from =1, to = 10, length.out = n)
y_deterministic <- a + b*x
pvals <- integer(length = 1000)

y_simulated <-rnorm(length(x), mean = y_deterministic, sd = rse)
mod_sim <- lm(y_simulated ~ x)
print(summary(mod_sim)$coef[2,4])

}

p_val(0.5, 0.1, 20, 3)

# to confirm it works, put set.seed() in the function

```

```{r}

# Run 1000 times

hist_thousand <- function(a, b, n, rse){
  
x <- seq(from =1, to = 10, length.out = n)
y_deterministic <- a + b*x
pvals <- integer(length = 1000)

for(i in 1:1000) {
y_simulated <-rnorm(length(x), mean = y_deterministic, sd = rse)
mod_sim <- lm(y_simulated ~ x)
p_val_slope <- summary(mod_sim)$coef[2,4]
pvals[i] <- p_val_slope 
}

hist(pvals, ylim = c(0,200), main = "Frequency of P Values", xlab = "P Values")
punder0.05 <- which(pvals < 0.05)
print("Proportion of P-Values Less than 0.05")
print(length(punder0.05)/1000)
}

hist_thousand(0.5, 0.1, 20, 1.5)


```


```{r}

# Change to slope = 0

hist_thousand(0.5, 0, 20, 1.5)

# The histogram is more evenly distributed. Around 50/50 for above or below P = 0.05
# There was a much greater frequency of P values under 0.05 when slope = 0.1
# This is because the slope & intercept make the points for the line fitting the curve. Setting slope = 0 fits the points to a straight line & no relationship between x & y is observed. The P values show nothing significant in this case.


```

```{r}

# slope = 0.1, a = 0.5, rse = 1.5
# for loop

pval_loop <- function(a, b, rse){
  
pvals <- integer()
forplot <- matrix(data = NA, nrow = 19, ncol = 2)
n=10

for(j in 1:10000){

x <- seq(from =1, to = 10, length.out = n)
y_deterministic <- a + b*x
  
for(i in 1:100) {
y_simulated <-rnorm(length(x), mean = y_deterministic, sd = rse)
mod_sim <- lm(y_simulated ~ x)
p_val_slope <- summary(mod_sim)$coef[2,4]
pvals[i] <- p_val_slope
}

punder0.05 <- which(pvals < 0.05) # count ones under 0.05
forplot[j,2] <- (length(punder0.05))/100
forplot[j,1] <- n
n =  n + 5
if( n > 100){ 
break
}
}
print(forplot)
plot( x = forplot[,1], y = forplot[,2], type = "p", xlab = "Sample Size", ylab = "Proportion < 0.05", main = "Effect of Sample size on P Value", col = "red", pch = 16)
}

pval_loop(0.5, 0.1, 1.5)



```



